"""Send the issuer pre-notification bundles through SES.

The bundles are generated by `gnw notify` into data/notify/<snapshot>/<issuer>/.
This script does the one step the pipeline deliberately refuses to do, because
sending mail to 185 real companies should be a human decision with a dry run in
front of it.

Design notes, all of them learned from how this can go wrong:

* Dry run is the default. Nothing sends unless --send is passed.
* A send ledger (data/notify/<snapshot>/sent.json) records every accepted
  message id. Re-running skips issuers already in the ledger, so an interrupted
  run resumes instead of double-notifying. The ledger is the audit trail behind
  the claim that each issuer was notified before publication.
* Rate limited to the account's real max send rate, fetched from SES rather
  than assumed.
* A bounce means an issuer was never notified, which silently breaks the
  14-day promise. The SES configuration set routes bounces to SNS; this script
  additionally re-reads the ledger at the end and prints who is unconfirmed.
* Attachments are the evidence files as generated. No zipping, so a recipient
  can open one file without unpacking everything.

Usage:
    python ops/send_notifications.py --snapshot 2026-09 --publish-date 2026-10-26
    python ops/send_notifications.py --snapshot 2026-09 --publish-date 2026-10-26 --send
    python ops/send_notifications.py --snapshot 2026-09 --only 10091 --send
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import re
import sys
import time
from email.message import EmailMessage
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

REPO = Path(__file__).resolve().parents[1]
FROM_DEFAULT = "contact@ghostnetworkwatch.org"
CONFIG_SET = "gnw-notify"
REGION = "us-east-1"
# Guardrail: the PUF has ~185 issuers. A number far above that means something
# is wrong with the bundle directory, and blasting mail is not recoverable.
MAX_RECIPIENTS = 400


def parse_draft(path: Path) -> tuple[str, str, str]:
    """Split draft_email.txt into (to, subject, body)."""
    raw = path.read_text()
    head, _, body = raw.partition("\n\n")
    to = subject = ""
    for line in head.splitlines():
        if line.lower().startswith("to:"):
            to = line.split(":", 1)[1].strip()
        elif line.lower().startswith("subject:"):
            subject = line.split(":", 1)[1].strip()
    if not to or not subject:
        raise ValueError(f"{path}: could not find To: and Subject: headers")
    if not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", to):
        raise ValueError(f"{path}: recipient {to!r} does not look like an address")
    return to, subject, body.strip()


def build_message(bundle: Path, sender: str, reply_to: str) -> EmailMessage:
    to, subject, body = parse_draft(bundle / "draft_email.txt")
    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = to
    msg["Subject"] = subject
    if reply_to and reply_to != sender:
        msg["Reply-To"] = reply_to
    msg.set_content(body)
    for f in sorted(bundle.iterdir()):
        if f.name == "draft_email.txt" or not f.is_file():
            continue
        ctype, encoding = mimetypes.guess_type(f.name)
        if encoding == "gzip":
            maintype, subtype = "application", "gzip"
        elif ctype:
            maintype, subtype = ctype.split("/", 1)
        else:
            maintype, subtype = "application", "octet-stream"
        msg.add_attachment(
            f.read_bytes(), maintype=maintype, subtype=subtype, filename=f.name
        )
    return msg


def load_ledger(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text())
    return {}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--snapshot", required=True, help="e.g. 2026-09")
    ap.add_argument("--send", action="store_true",
                    help="actually send; without this it is a dry run")
    ap.add_argument("--only", help="one issuer id, for a single test send")
    ap.add_argument("--from", dest="sender", default=FROM_DEFAULT)
    ap.add_argument("--reply-to", default="")
    args = ap.parse_args()

    root = REPO / "data" / "notify" / args.snapshot
    if not root.is_dir():
        print(f"no bundles at {root}. Run: gnw notify --snapshot {args.snapshot}")
        return 1

    bundles = sorted(d for d in root.iterdir() if d.is_dir())
    if args.only:
        bundles = [d for d in bundles if d.name == args.only]
        if not bundles:
            print(f"issuer {args.only} has no bundle under {root}")
            return 1

    ledger_path = root / "sent.json"
    ledger = load_ledger(ledger_path)
    todo = [b for b in bundles if b.name not in ledger]

    print(f"snapshot {args.snapshot}: {len(bundles)} bundle(s), "
          f"{len(ledger)} already sent, {len(todo)} to send")
    if len(todo) > MAX_RECIPIENTS:
        print(f"refusing: {len(todo)} recipients exceeds the {MAX_RECIPIENTS} guardrail")
        return 1
    if not todo:
        print("nothing to do")
        return 0

    ses = boto3.client("sesv2", region_name=REGION)
    acct = ses.get_account()
    rate = float(acct["SendQuota"]["MaxSendRate"])
    if args.send and not acct.get("ProductionAccessEnabled"):
        print("SES is still in the sandbox: sending would fail for any recipient "
              "that is not separately verified. Request production access first.")
        return 1
    delay = 1.0 / rate if rate else 1.0

    # Validate every message before sending any of them. A malformed draft
    # halfway through a run leaves the notification set half-delivered.
    built = []
    total_mb = 0.0
    for b in todo:
        msg = build_message(b, args.sender, args.reply_to)
        size = len(msg.as_bytes()) / 1e6
        total_mb += size
        if size > 9.5:
            print(f"  {b.name}: {size:.1f} MB exceeds the SES 10 MB message limit")
            return 1
        built.append((b, msg))
    print(f"all {len(built)} message(s) built, {total_mb:.1f} MB total, "
          f"send rate {rate}/s")

    if not args.send:
        b, msg = built[0]
        print("\n--- DRY RUN, first message ---")
        print(f"issuer {b.name}  ->  {msg['To']}")
        print(f"subject: {msg['Subject']}")
        atts = [p.get_filename() for p in msg.iter_attachments()]
        print(f"attachments: {', '.join(atts)}")
        print(f"\n{msg.get_body(preferencelist=['plain']).get_content()[:700]}")
        print("--- end dry run. Re-run with --send to deliver. ---")
        return 0

    sent = failed = 0
    for b, msg in built:
        try:
            resp = ses.send_email(
                FromEmailAddress=args.sender,
                Destination={"ToAddresses": [msg["To"]]},
                Content={"Raw": {"Data": msg.as_bytes()}},
                ConfigurationSetName=CONFIG_SET,
            )
            ledger[b.name] = {
                "to": msg["To"],
                "message_id": resp["MessageId"],
                "sent_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            }
            sent += 1
            print(f"  sent {b.name} -> {msg['To']}")
        except ClientError as e:
            failed += 1
            print(f"  FAILED {b.name} -> {msg['To']}: "
                  f"{e.response['Error'].get('Message', e)}")
        finally:
            # Write after every message: an interrupted run must not lose the
            # record of what already went out.
            ledger_path.write_text(json.dumps(ledger, indent=1, sort_keys=True))
        time.sleep(delay)

    print(f"\nsent {sent}, failed {failed}, ledger at {ledger_path}")
    print("Watch for bounce notifications: a bounce means that issuer was not "
          "actually notified, and the 14-day window has not started for them.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
